spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/datapulse_db
    username: rupeshmacbook
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create  # Keep as 'create' for now
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

logging:
  level:
    org.hibernate.SQL: DEBUG