spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/datapulse_db
    username: rupeshmacbook
    password: rupesh@123
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true

server:
  port: 8082
